version = 1

[[analyzers]]
name = "python"

[[analyzers]]
name = "go"

[[analyzers]]
name = "javascript"

[[analyzers]]
name = "java"

[[analyzers]]
name = "ruby"

[[analyzers]]
name = "rust"

[[analyzers]]
name = "kotlin"

[[analyzers]]
name = "swift"

[[analyzers]]
name = "cxx"

[[analyzers]]
name = "csharp"

[[analyzers]]
name = "scala"

[[analyzers]]
name = "php"

[[analyzers]]
name = "docker"

[[analyzers]]
name = "terraform"

[[analyzers]]
name = "ansible"

[[analyzers]]
name = "shell"

[[analyzers]]
name = "sql
