version = 1

[[analyzers]]
name = "python"

[[analyzers]]
name = "go"

[[analyzers]]
name = "javascript"

[[analyzers]]
name = "java"

[[analyzers]]
name = "ruby"

[[analyzers]]
name = "rust"

[[analyzers]]
name = "kotlin"

[[analyzers]]
name = "swift"

[[analyzers]]
name = "cxx"

[[analyzers]]
name = "csharp"

[[analyzers]]
name = "scala"

[[analyzers]]
name = "php"

[[analyzers]]
name = "docker"

[[analyzers]]
name = "terraform"

[[analyzers]]
name = "ansible"

[[analyzers]]
name = "shell"

[[analyzers]]
name = "sql

[[code_formatters]]
name = "prettier"
enabled = true

[[code_formatters]]
name = "standardjs"
enabled = true

[[code_formatters]]
name = "rubocop"
enabled = true

[[code_formatters]]
name = "standardrb"
enabled = true

[[code_formatters]]
name = "google-java-format"
enabled = true

[[code_formatters]]
name = "scalafmt"
enabled = true

[[code_formatters]]
name = "dotnet-format"

[[code_formatters]]
name = "clang-format"

[[code_formatters]]
name = "php-cs-fixer"

[[code_formatters]]
name = "ktlint"

[[code_formatters]]
name = "swift-format"
